connection: propel
noXsd: false
defaultIdMethod: native
package: plugins.iceSpamControlPlugin.lib.model
encoding: utf8

classes:
  SpamControl:
    phpName: iceModelSpamControl
    columns:
      id:           ~
      field:        { type: enum, valueSet: "email, phone, ip, regex, session", default: 'regex', required: true }
      value:        { type: varchar, size: 64, required: true }
      credentials:  { type: enum, valueSet: "all, read, create, edit, comment", default: 'read', required: true }
      is_banned:    { type: boolean, sqlType: "BOOL", required: true, default: false }
      is_throttled: { type: boolean, sqlType: "BOOL", required: true, default: false }

    uniques:
      spam_control_U_1: [field, credentials, value]

    propel_behaviors:
      timestampable:  ~
